### ISSUE TITLE
Add brunch-config.coffee file to Add Item (client-side) dialog.

### ISSUE THREAD

**Issue by Bartmax** [madskristensen/BrunchTaskRunner#2]
referenced from https://github.com/aspnet/Tooling/issues/37

**Comment by madskristensen** [comment]
I just confirmed that a VSIX can ship multiple items templates, so that's awesome. What should the content of the **brunch-config.coffee** item template be? 

Also, should we also add a **brunch-config.js** template?

**Comment by Bartmax** [comment]
Great!! I think this is a good default:

``` coffeescript
exports.config =
  # See http://brunch.io/#documentation for docs.
  paths:
    public: 'wwwroot'
  files:
    javascripts:
      joinTo: 
        'js/app.js' : /^app/
        'js/libs.js': /(vendor|bower_components)/
    stylesheets:
      joinTo: 
        '/css/app.css' : /^app/
        '/css/libs.css' : /(vendor|bower_components)/
  modules: 
    wrapper: false
```

while `brunch-config.js` is a supported "type", it's not common. I wouldn't include it.

**Comment by Bartmax** [comment]
FYI: in **DNX** projects, this is somehow out of place.

![image](https://cloud.githubusercontent.com/assets/3386797/10810712/ef149648-7dea-11e5-84a0-420344169eeb.png)

**Comment by madskristensen** [comment]
The DNX top level node is changing to something else. I will move it after the change
